# Build settings
plugins:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Alexey Zagalsky"
description: > # this means to ignore newlines until "email:"
    Software Engineering Researcher

email: alexeyza@gmail.mail
#blog logo
logo: "/assets/images/az_logo.png"
float_logo: true # true, false (default)
# blog cover
cover: "/assets/images/background.jpg"

name: 'Alexey Zagalsky'
author: 'Alexey Zagalsky'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "http://alexeyza.com" # the base hostname & protocol for your site
baseurl: ""

excerpt_separator: "<!--more-->"
permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

#used to display twitter cards
twitter_handle: '@alexeyzagalsky'

#fill in disqus shortname to use disqus
disqus: alexeyzablog

#Google analytics ID
google_analytics: UA-54265697-1

# social icons and sharing options
social:
  - icon:  envelope
    fa5: fas
    url: mailto:alexeyza@gmail.com
    desc: Contact me by email
    share_url:
    share_title:
    share_link:

  - icon:	twitter
    fa5: fab
    url:	https://twitter.com/alexeyzagalsky
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="
    share_author: "%20by%20%40alexeyzagalsky"

  - icon:	github
    fa5: fab
    url:	https://github.com/alexeyza
    desc:	Follow me on Github
    share_url:
    share_title:
    share_link:

  - icon:  stack-overflow
    fa5: fab
    url: https://stackoverflow.com/users/257760/alexey-zagalsky
    desc: My activity on Stack Overflow
    share_url:
    share_title:
    share_link:

  - icon:  500px
    fa5: fab
    url: https://500px.com/alexeyza
    desc: See my photos on 500px
    share_url:
    share_title:
    share_link:

  - icon:  linkedin
    fa5: fab
    url: https://linkedin.com/in/alexeyza
    desc: Find me on Linkedin
    share_url: https://www.linkedin.com/shareArticle
    share_title: ?title=
    share_link: "&amp;url="

  - icon:  slideshare
    fa5: fab
    url: https://speakerdeck.com/alexeyza
    desc: See my slides on Speaker Deck
    share_url:
    share_title:
    share_link:

academics:
  - icon:  google-scholar
    url: https://scholar.google.ca/citations?user=WWYRn7AAAAAJ
    desc: See my publications on Google Scholar
    share_url:
    share_title:
    share_link:

#  - icon:  facebook
#    url: https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
